-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 19:04:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`producto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`producto` (
  `producto_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT(11) NOT NULL,
  `url_imagen` VARCHAR(255) NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`rol` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`rol` (
  `rol_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`usuario` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(70) NOT NULL,
  `rol_rol_id` INT(11) NOT NULL,
  `url_foto` VARCHAR(255) NULL DEFAULT NULL,
  `baja` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`usuario_id`, `rol_rol_id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  INDEX `fk_usuario_rol_idx` (`rol_rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_rol_id`)
    REFERENCES `ecommerce`.`rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
